### PR TITLE
FrackinUniverse hardcore fix

### PR DESCRIPTION
**Pull request by ghost**
Added a respawnhardcore.cinematic so Inklings don't stay dead when killed on Frackin hardcore mode. I also tested it without FU, the game seems to ignore it and they stay permadead as intended. (Not sure if it would still work if the mods load in a different order, though... Hopefully.)

Also shaved a few unneeded pixels from the body .pngs so they don't clip through their clothes with certain personality poses.

### CODE REVIEW

**Comment by marinebeast** [comment]
Thanks for the contribution! I'll give this a look-over-- thanks for testing it without FU!

**Comment by DeltaJordan** [comment]
I want to note that the latest version of Squids in Space is not fully aligned with the master branch (yet). If possible please wait until I align the repo with the latest release. Side note, Please Please if you are committing anything to the repo do NOT use the in-browser upload/delete files that GitHub has. Look up git tutorials and/or use GitHub Desktop. Accidentally closed this my bad I'm on mobile so it's pretty annoying to use.

**Comment by DeltaJordan** [comment]
Git is a very useful skill to learn especially if you plan on working with tech

**Comment by DeltaJordan** [comment]
I recommend this: https://kbroman.org/github_tutorial/

**Comment by ghost** [comment]
I don't plan on doing anything "serious" tech-related in the near future, I'm just here because game modding is a hobby of mine... and because I love Splatoon. But still, I'm not *unwilling* to learn other stuff so thanks for the advice. Out of curiosity though what's wrong with using the browser to upload files? Does it have issues I'm unaware of?

**Comment by DeltaJordan** [comment]
Sorry for the late response; using the browser upload system adds a commit for every file
image

Using git its all one commit all at once. Plus you can add a commit message to explain what you did. Git also helps prevent missing files or duplicates. Having a local repo is like having a folder on your computer that you can update on demand to match the remote.

**Comment by DeltaJordan** [comment]
This has been implemented in #9 

Thank you for your contribution!

**Pull request closed without merging**
